#!/usr/bin/env bash
# brain-training-digest.sh - Weekly digest for brain-training mode.
#
# Reads $VAULT_PATH and produces a markdown digest covering:
#   1. Reviews due in the next 7 days
#   2. Convergences detected in the past 7 days
#   3. Unresolved cross-video tensions
#   4. Stagnant clusters (no ingest in 60+ days)
#   5. Top speakers in the past 30 days
#   6. Network concentration gaps
#   7. Active recall completion rate
#
# Usage:
#   ./brain-training-digest.sh [output_path]
#
# Reads config from config.yml at repo root or env vars:
#   VAULT_PATH, KNOWLEDGE_CONTAINER, PERSONS_CONTAINER

set -euo pipefail

# --- config ---
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONFIG_FILE="$REPO_ROOT/config.yml"

if [[ -f "$CONFIG_FILE" ]]; then
  # Naive YAML parser for flat key: value pairs
  while IFS=': ' read -r key value; do
    [[ -z "$key" || "$key" =~ ^# ]] && continue
    value="${value%\"}"; value="${value#\"}"
    eval "${key}='${value/#\~/$HOME}'" 2>/dev/null || true
  done < <(grep -E '^[A-Z_]+:' "$CONFIG_FILE" | sed 's/^/export /' | sed 's/: /=/')
fi

VAULT_PATH="${VAULT_PATH:-$HOME/Documents/MyVault}"
KNOWLEDGE_CONTAINER="${KNOWLEDGE_CONTAINER:-Knowledge Library}"
PERSONS_CONTAINER="${PERSONS_CONTAINER:-Persons}"
QA_CONTAINER="Q&A"
TENSIONS_CONTAINER="Tensions"

OUT_PATH="${1:-$HOME/Desktop/brain-training-digest-$(date +%Y-%m-%d).md}"

KNOWLEDGE_DIR="$VAULT_PATH/$KNOWLEDGE_CONTAINER"
PERSONS_DIR="$VAULT_PATH/$PERSONS_CONTAINER"
QA_DIR="$VAULT_PATH/$QA_CONTAINER"
TENSIONS_DIR="$VAULT_PATH/$TENSIONS_CONTAINER"

[[ -d "$KNOWLEDGE_DIR" ]] || { echo "Knowledge container not found: $KNOWLEDGE_DIR" >&2; exit 1; }

TODAY=$(date +%Y-%m-%d)
DATE_7=$(date -v+7d +%Y-%m-%d 2>/dev/null || date -d "+7 days" +%Y-%m-%d)
DATE_M30=$(date -v-30d +%Y-%m-%d 2>/dev/null || date -d "-30 days" +%Y-%m-%d)
DATE_M60=$(date -v-60d +%Y-%m-%d 2>/dev/null || date -d "-60 days" +%Y-%m-%d)

# --- helpers ---
extract_fm() {
  # extract_fm <file> <key>  -> value or empty
  awk -v k="$2" '
    /^---$/ { in_fm = !in_fm; next }
    in_fm && $1 == k":" { sub("^[^:]+: ", ""); gsub(/^\s+|\s+$/, ""); print; exit }
  ' "$1"
}

# --- write digest ---
cat > "$OUT_PATH" <<EOF
# Brain Training Digest - $TODAY

Generated by youtube-ingest-skill weekly digest.
Vault: $VAULT_PATH

EOF

# 1. Reviews due
echo "## 1. Reviews due in the next 7 days" >> "$OUT_PATH"
echo "" >> "$OUT_PATH"
DUE_COUNT=0
if [[ -d "$QA_DIR" ]]; then
  while IFS= read -r -d '' qa_file; do
    next_review=$(extract_fm "$qa_file" "next_review")
    [[ -z "$next_review" ]] && continue
    if [[ "$next_review" < "$DATE_7" || "$next_review" == "$DATE_7" ]]; then
      source=$(extract_fm "$qa_file" "source")
      basename_qa=$(basename "$qa_file")
      echo "- **$next_review** - [[${basename_qa%.md}]] (source: $source)" >> "$OUT_PATH"
      DUE_COUNT=$((DUE_COUNT + 1))
    fi
  done < <(find "$QA_DIR" -name "*.md" -print0 2>/dev/null)
fi
[[ $DUE_COUNT -eq 0 ]] && echo "_No reviews due. Either you are caught up, or active recall is not being used._" >> "$OUT_PATH"
echo "" >> "$OUT_PATH"
echo "_Total due: $DUE_COUNT_" >> "$OUT_PATH"
echo "" >> "$OUT_PATH"

# 2. Convergences detected in past 7 days
echo "## 2. Convergences detected (past 7 days)" >> "$OUT_PATH"
echo "" >> "$OUT_PATH"
CONV_COUNT=0
while IFS= read -r -d '' note; do
  date=$(extract_fm "$note" "date")
  [[ -z "$date" ]] && continue
  if [[ "$date" > "$(date -v-7d +%Y-%m-%d 2>/dev/null || date -d '-7 days' +%Y-%m-%d)" ]]; then
    if grep -q "^## Convergence" "$note" 2>/dev/null; then
      title=$(basename "$note" .md)
      weight=$(grep -A 10 "^## Convergence" "$note" | grep -oE "Convergence weight: [A-Z]+" | head -1)
      echo "- [[$title]] - $weight" >> "$OUT_PATH"
      CONV_COUNT=$((CONV_COUNT + 1))
    fi
  fi
done < <(find "$KNOWLEDGE_DIR" -name "*.md" -print0 2>/dev/null)
[[ $CONV_COUNT -eq 0 ]] && echo "_No new convergences this week._" >> "$OUT_PATH"
echo "" >> "$OUT_PATH"

# 3. Unresolved tensions
echo "## 3. Unresolved cross-video tensions" >> "$OUT_PATH"
echo "" >> "$OUT_PATH"
TENS_COUNT=0
while IFS= read -r -d '' note; do
  if grep -q "^## Cross-video tension" "$note" 2>/dev/null; then
    status=$(extract_fm "$note" "tension")
    [[ "$status" == "resolved" ]] && continue
    title=$(basename "$note" .md)
    date=$(extract_fm "$note" "date")
    echo "- [[$title]] (opened $date)" >> "$OUT_PATH"
    TENS_COUNT=$((TENS_COUNT + 1))
  fi
done < <(find "$KNOWLEDGE_DIR" -name "*.md" -print0 2>/dev/null)
[[ $TENS_COUNT -eq 0 ]] && echo "_No open tensions. Either your graph is consistent, or you are not flagging contradictions._" >> "$OUT_PATH"
echo "" >> "$OUT_PATH"

# 4. Stagnant clusters
echo "## 4. Stagnant clusters (no ingest in 60+ days)" >> "$OUT_PATH"
echo "" >> "$OUT_PATH"
declare -A CLUSTER_LAST
while IFS= read -r -d '' note; do
  date=$(extract_fm "$note" "date")
  tags=$(extract_fm "$note" "tags")
  cluster=$(echo "$tags" | grep -oE "cluster: [a-z_-]+" | head -1 | sed 's/cluster: //')
  [[ -z "$cluster" || -z "$date" ]] && continue
  if [[ -z "${CLUSTER_LAST[$cluster]:-}" || "$date" > "${CLUSTER_LAST[$cluster]}" ]]; then
    CLUSTER_LAST[$cluster]="$date"
  fi
done < <(find "$KNOWLEDGE_DIR" -name "*.md" -print0 2>/dev/null)

STAG_COUNT=0
for cluster in "${!CLUSTER_LAST[@]}"; do
  last="${CLUSTER_LAST[$cluster]}"
  if [[ "$last" < "$DATE_M60" ]]; then
    echo "- **$cluster** - last ingest: $last" >> "$OUT_PATH"
    STAG_COUNT=$((STAG_COUNT + 1))
  fi
done
[[ $STAG_COUNT -eq 0 ]] && echo "_No stagnant clusters. Your learning network is active across all topics._" >> "$OUT_PATH"
echo "" >> "$OUT_PATH"

# 5. Top speakers past 30 days
echo "## 5. Top speakers (past 30 days)" >> "$OUT_PATH"
echo "" >> "$OUT_PATH"
declare -A SPEAKER_COUNT
while IFS= read -r -d '' note; do
  date=$(extract_fm "$note" "date")
  author=$(extract_fm "$note" "author")
  [[ -z "$author" || -z "$date" ]] && continue
  if [[ "$date" > "$DATE_M30" ]]; then
    SPEAKER_COUNT[$author]=$((${SPEAKER_COUNT[$author]:-0} + 1))
  fi
done < <(find "$KNOWLEDGE_DIR" -name "*.md" -print0 2>/dev/null)

if [[ ${#SPEAKER_COUNT[@]} -gt 0 ]]; then
  for speaker in "${!SPEAKER_COUNT[@]}"; do
    echo "${SPEAKER_COUNT[$speaker]} $speaker"
  done | sort -rn | head -10 | while read -r count speaker; do
    echo "- **$count neurons** - $speaker" >> "$OUT_PATH"
  done
else
  echo "_No ingests in past 30 days._" >> "$OUT_PATH"
fi
echo "" >> "$OUT_PATH"

# 6. Network concentration gaps
echo "## 6. Network concentration gaps" >> "$OUT_PATH"
echo "" >> "$OUT_PATH"
declare -A CLUSTER_SPEAKERS
while IFS= read -r -d '' note; do
  author=$(extract_fm "$note" "author")
  tags=$(extract_fm "$note" "tags")
  cluster=$(echo "$tags" | grep -oE "cluster: [a-z_-]+" | head -1 | sed 's/cluster: //')
  [[ -z "$cluster" || -z "$author" ]] && continue
  CLUSTER_SPEAKERS[$cluster]+="|$author"
done < <(find "$KNOWLEDGE_DIR" -name "*.md" -print0 2>/dev/null)

GAP_COUNT=0
for cluster in "${!CLUSTER_SPEAKERS[@]}"; do
  uniq_speakers=$(echo "${CLUSTER_SPEAKERS[$cluster]}" | tr '|' '\n' | sort -u | grep -v '^$' | wc -l | tr -d ' ')
  if [[ "$uniq_speakers" -eq 1 ]]; then
    echo "- **$cluster** - only 1 speaker (concentration risk)" >> "$OUT_PATH"
    GAP_COUNT=$((GAP_COUNT + 1))
  fi
done
[[ $GAP_COUNT -eq 0 ]] && echo "_All clusters have multiple speakers. Healthy network diversity._" >> "$OUT_PATH"
echo "" >> "$OUT_PATH"

# 7. Active recall completion rate
echo "## 7. Active recall completion rate" >> "$OUT_PATH"
echo "" >> "$OUT_PATH"
if [[ -d "$QA_DIR" ]]; then
  TOTAL_QA=$(find "$QA_DIR" -name "*.md" 2>/dev/null | wc -l | tr -d ' ')
  DUE_QA=0
  REVIEWED_QA=0
  while IFS= read -r -d '' qa_file; do
    next_review=$(extract_fm "$qa_file" "next_review")
    [[ -z "$next_review" ]] && continue
    if [[ "$next_review" < "$TODAY" || "$next_review" == "$TODAY" ]]; then
      DUE_QA=$((DUE_QA + 1))
    fi
  done < <(find "$QA_DIR" -name "*.md" -print0 2>/dev/null)
  COMPLETION=$(( (TOTAL_QA - DUE_QA) * 100 / (TOTAL_QA > 0 ? TOTAL_QA : 1) ))
  echo "- Total Q&A files: $TOTAL_QA" >> "$OUT_PATH"
  echo "- Currently overdue: $DUE_QA" >> "$OUT_PATH"
  echo "- Completion rate: ${COMPLETION}%" >> "$OUT_PATH"
  if [[ $COMPLETION -lt 60 ]]; then
    echo "" >> "$OUT_PATH"
    echo "_WARNING: completion rate below 60%. Brain training requires active recall. Either ingest less or review more._" >> "$OUT_PATH"
  fi
else
  echo "_No Q&A folder. Active recall is not being used._" >> "$OUT_PATH"
fi
echo "" >> "$OUT_PATH"

echo "---" >> "$OUT_PATH"
echo "_Generated $TODAY by brain-training-digest.sh_" >> "$OUT_PATH"

echo "Digest written to: $OUT_PATH"
